site_name: Documentação

nav:
  - Instruções mkdocs: "index.md"
  - Documento de Visão: "documento-visao/documento-visao.md"
  - Documento de Requisitos: "documento-requisitos/documento-requisitos.md"
  - Documento de Arquitetura: "documento-arquitetura/documento-arquitetura.md"
  - Documento de Plano de Testes: "documento-plano-testes/documento-plano-testes.md"
  - Atas de Reunião:
    - 1 - Requisitos: "atas-reuniao/ata-reuniao-1.md"
    - 2 - Formulário de player: "atas-reuniao/ata-reuniao-2.md"
    - 3 - Validação de requisitos: "atas-reuniao/ata-reuniao-3.md"
    - 4 - Análise de player e tema do PGG: "atas-reuniao/ata-reuniao-4.md"
    - 5 - Planejamento do Front-End: "atas-reuniao/ata-reuniao-5.md"
    - 6 - Validação de requisitos e análise do tema do PGG: "atas-reuniao/ata-reuniao-6.md"
    - 7 - Documento de visão: "atas-reuniao/ata-reuniao-7.md"
    - 8 - Relatório da análise de player: "atas-reuniao/ata-reuniao-8.md"
  - Documentos sobre gamificação: 
    - Relatório do formulário: "documentos-gamificacao/relatorio-formulario.md"

theme:
  name: material
