
services:
  postgres:
    container_name: wunjo.backend.pg
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wnjo-backend
    volumes:
      - wunjo-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - wunjo_network
  redis:
    container_name: wunjo.account.redis
    image: redis:7.2.4
    env_file:
      - env/.env.local
    command: redis-server --save 20 1 --loglevel warning
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - wunjo_network
  server:
    container_name: wunjo.backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      #- postgres
      - redis
    volumes:
      - ".:/usr/app"
    command: npm run prod
    networks:
      - wunjo_network

networks:
  wunjo_network:
    driver: bridge

volumes:
  wunjo-db:
  cache:
    driver: local