#!/usr/bin/env sh
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

echo -e "\n${yellow}Executing pre-commit hook${no_color}\n"


echo -e "\n${yellow}Running lint${no_color}\n"

echo -e "\n${green}Lint passed${no_color}\n"